FROM maven:3.9.9-eclipse-temurin-21-alpine AS build

LABEL org.opencontainers.image.authors="gustavoprasca@hotmail.com"
WORKDIR api
COPY ../pom.xml .
## descarga las dependencias
RUN mvn clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/
##RUN mvn dependency:go-offline
COPY ../src ./src
RUN mvn clean package -DskipTests


FROM eclipse-temurin:21-jre-alpine

WORKDIR /home/microservice-user
COPY --from=build /api/target/*.jar ./api-microservice-user-mysql.jar
EXPOSE 9092
ENTRYPOINT ["java","-jar","./api-microservice-user-mysql.jar"]